name: todo_app
description: This is a TO DO app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  collection: ^1.17.2
  data_channel: ^2.0.0+1
  dio: ^5.4.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/core/constants/
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/